In [19]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import Dataset

import math

import numpy as np
import pandas as pd

import os
import os.path as osp

import matplotlib.pyplot as plt

In [20]:
root = "/home/paokimsiwoong/workspace/github.com/paokimsiwoong/ml_practice/transformer/my_dataset"
dest = "/home/paokimsiwoong/workspace/github.com/paokimsiwoong/ml_practice/transformer/my_real_dataset"

In [21]:
file_list = os.listdir(root)
file_list

['1_구어체(1).xlsx',
 '3_문어체_뉴스(2).xlsx',
 '4_문어체_한국문화.xlsx',
 '2_대화체.xlsx',
 '3_문어체_뉴스(1).xlsx',
 '1_구어체(2).xlsx',
 '3_문어체_뉴스(3).xlsx',
 '3_문어체_뉴스(4).xlsx',
 '5_문어체_조례.xlsx',
 '6_문어체_지자체웹사이트.xlsx']

In [22]:
for name in file_list:
    print("".center(50, "-"))
    print("".center(50, "-"))
    file_path = osp.join(root, name)
    new_name = name[:-5] + ".csv"
    new_file_path = osp.join(dest, new_name)
    df = pd.read_excel(file_path, engine='openpyxl')
    print(name)
    print(df.shape)
    print(df.columns)
    print("".center(50, "-"))
    df.columns = ['kor', 'en', 'cat']
    category = name.split('_')[0]
    print(f"==>> category: {category}")
    print(name)
    print(df.shape)
    print(df.columns)
    print(df.isnull().sum())
    df.to_csv(new_file_path, index=False)

--------------------------------------------------
--------------------------------------------------
1_구어체(1).xlsx
(200000, 3)
Index(['원문', '번역문', '분류'], dtype='object')
--------------------------------------------------
==>> category: 1
1_구어체(1).xlsx
(200000, 3)
Index(['kor', 'en', 'cat'], dtype='object')
kor    0
en     0
cat    0
dtype: int64
--------------------------------------------------
--------------------------------------------------
3_문어체_뉴스(2).xlsx
(200541, 3)
Index(['원문', '번역문', '분류'], dtype='object')
--------------------------------------------------
==>> category: 3
3_문어체_뉴스(2).xlsx
(200541, 3)
Index(['kor', 'en', 'cat'], dtype='object')
kor    0
en     0
cat    0
dtype: int64
--------------------------------------------------
--------------------------------------------------
4_문어체_한국문화.xlsx
(100646, 3)
Index(['원문', '번역문', '분류'], dtype='object')
--------------------------------------------------
==>> category: 4
4_문어체_한국문화.xlsx
(100646, 3)
Index(['kor', 'en', 'cat'], dtype='object')
kor    0
en     0
cat    0
dtype: int64
--------------------------------------------------
--------------------------------------------------
2_대화체.xlsx
(100000, 3)
Index(['원문', '번역문', '분류'], dtype='object')
--------------------------------------------------
==>> category: 2
2_대화체.xlsx
(100000, 3)
Index(['kor', 'en', 'cat'], dtype='object')
kor    0
en     0
cat    0
dtype: int64
--------------------------------------------------
--------------------------------------------------
3_문어체_뉴스(1).xlsx
(200011, 3)
Index(['원문', '번역문', '분류'], dtype='object')
--------------------------------------------------
==>> category: 3
3_문어체_뉴스(1).xlsx
(200011, 3)
Index(['kor', 'en', 'cat'], dtype='object')
kor    0
en     0
cat    0
dtype: int64
--------------------------------------------------
--------------------------------------------------
1_구어체(2).xlsx
(200000, 3)
Index(['원문', '번역문', '분류'], dtype='object')
--------------------------------------------------
==>> category: 1
1_구어체(2).xlsx
(200000, 3)
Index(['kor', 'en', 'cat'], dtype='object')
kor    0
en     0
cat    0
dtype: int64
--------------------------------------------------
--------------------------------------------------
3_문어체_뉴스(3).xlsx
(200835, 3)
Index(['원문', '번역문', '분류'], dtype='object')
--------------------------------------------------
==>> category: 3
3_문어체_뉴스(3).xlsx
(200835, 3)
Index(['kor', 'en', 'cat'], dtype='object')
kor    0
en     0
cat    0
dtype: int64
--------------------------------------------------
--------------------------------------------------
3_문어체_뉴스(4).xlsx
(200000, 3)
Index(['원문', '번역문', '분류'], dtype='object')
--------------------------------------------------
==>> category: 3
3_문어체_뉴스(4).xlsx
(200000, 3)
Index(['kor', 'en', 'cat'], dtype='object')
kor    0
en     0
cat    0
dtype: int64
--------------------------------------------------
--------------------------------------------------
5_문어체_조례.xlsx
(100298, 3)
Index(['원문', '번역문', '분류'], dtype='object')
--------------------------------------------------
==>> category: 5
5_문어체_조례.xlsx
(100298, 3)
Index(['kor', 'en', 'cat'], dtype='object')
kor    0
en     0
cat    0
dtype: int64
--------------------------------------------------
--------------------------------------------------
6_문어체_지자체웹사이트.xlsx
(100087, 3)
Index(['원문', '번역문', '분류'], dtype='object')
--------------------------------------------------
==>> category: 6
6_문어체_지자체웹사이트.xlsx
(100087, 3)
Index(['kor', 'en', 'cat'], dtype='object')
kor    0
en     0
cat    0
dtype: int64

In [23]:
file_list = os.listdir(dest)
file_list

['3_문어체_뉴스(4).csv',
 '5_문어체_조례.csv',
 '2_대화체.csv',
 '1_구어체(1).csv',
 '4_문어체_한국문화.csv',
 '3_문어체_뉴스(2).csv',
 '6_문어체_지자체웹사이트.csv',
 '3_문어체_뉴스(3).csv',
 '1_구어체(2).csv',
 '3_문어체_뉴스(1).csv']

In [24]:
df_list = []
for file_name in file_list:
    file_path = osp.join(dest, file_name)
    df = pd.read_csv(file_path)
    df_list.append(df.copy())

data = pd.concat(df_list, ignore_index=True)

data.shape

(1602418, 3)

In [25]:
data.head()

,kor,en,cat
0,그 이후 그의 행방이 알려지지 않은 상황이다.,"Since then, his whereabouts are unknown.",2
1,그녀가 사라진 후 각종 의혹은 꼬리를 물었다.,Various doubts arose after she disappeared.,2
2,당연히 러시아인 승객이 제일 먼저 부름을 받았다.,"Naturally, Russian passengers were called first.",2
3,더 중요한 것은 고용이 대체적으로 안정됐다는 점이다.,"More importantly, employment is generally stable.",2
4,모세가 죽고 나서 이제 여호수아가 이스라엘을 이끌었습니다.,Joshua led Israel after Moses died.,2

In [26]:
grouped = data.groupby('cat')

In [27]:
cat1 = grouped.get_group(1)
cat1.head()

,kor,en,cat
300298,이번 신제품 출시에 대한 시장의 반응은 어떤가요?,How is the market's reaction to the newly rele...,1
300299,판매량이 지난번 제품보다 빠르게 늘고 있습니다.,The sales increase is faster than the previous...,1
300300,그렇다면 공장에 연락해서 주문량을 더 늘려야겠네요.,"Then, we'll have to call the manufacturer and ...",1
300301,"네, 제가 연락해서 주문량을 2배로 늘리겠습니다.","Sure, I'll make a call and double the volume o...",1
300302,지난 회의 마지막에 논의했던 안건을 다시 볼까요?,Shall we take a look at the issues we discusse...,1

In [28]:
final_dest = "/home/paokimsiwoong/workspace/github.com/paokimsiwoong/ml_practice/transformer/data.csv"

data.to_csv(final_dest, index=False)

In [29]:
load_data = pd.read_csv(final_dest)
load_data.head()

,kor,en,cat
0,그 이후 그의 행방이 알려지지 않은 상황이다.,"Since then, his whereabouts are unknown.",2
1,그녀가 사라진 후 각종 의혹은 꼬리를 물었다.,Various doubts arose after she disappeared.,2
2,당연히 러시아인 승객이 제일 먼저 부름을 받았다.,"Naturally, Russian passengers were called first.",2
3,더 중요한 것은 고용이 대체적으로 안정됐다는 점이다.,"More importantly, employment is generally stable.",2
4,모세가 죽고 나서 이제 여호수아가 이스라엘을 이끌었습니다.,Joshua led Israel after Moses died.,2

In [30]:
load_grouped = load_data.groupby('cat')

load_cat1 = load_grouped.get_group(1)
load_cat1.head()

,kor,en,cat
300298,이번 신제품 출시에 대한 시장의 반응은 어떤가요?,How is the market's reaction to the newly rele...,1
300299,판매량이 지난번 제품보다 빠르게 늘고 있습니다.,The sales increase is faster than the previous...,1
300300,그렇다면 공장에 연락해서 주문량을 더 늘려야겠네요.,"Then, we'll have to call the manufacturer and ...",1
300301,"네, 제가 연락해서 주문량을 2배로 늘리겠습니다.","Sure, I'll make a call and double the volume o...",1
300302,지난 회의 마지막에 논의했던 안건을 다시 볼까요?,Shall we take a look at the issues we discusse...,1

In [31]:
load_cat0 = load_grouped.get_group(0)
load_cat0.head()

,kor,en,cat
400298,'Bible Coloring'은 성경의 아름다운 이야기를 체험 할 수 있는 컬러링 ...,Bible Coloring' is a coloring application that...,0
400299,씨티은행에서 일하세요?,Do you work at a City bank?,0
400300,푸리토의 베스트셀러는 해외에서 입소문만으로 4차 완판을 기록하였다.,"PURITO's bestseller, which recorded 4th rough ...",0
400301,11장에서는 예수님이 이번엔 나사로를 무덤에서 불러내어 죽은 자 가운데서 살리셨습니다.,In Chapter 11 Jesus called Lazarus from the to...,0
400302,"6.5, 7, 8 사이즈가 몇 개나 더 재입고 될지 제게 알려주시면 감사하겠습니다.",I would feel grateful to know how many stocks ...,0